name: CI Artifactory SNAPSHOT Build for Maven

on:
  workflow_call:
    inputs:
      mavenArgs:
        description: 'Additional mvn command arguments: goals, plugins etc. The `install` is included.'
        required: false
        type: string

jobs:
  build_snapshot:
    runs-on: ubuntu-latest
    name: CI Build SNAPSHOT for ${{ github.ref_name }}
    steps:

      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
          cache: 'maven'

      - uses: jfrog/setup-jfrog-cli@v3
        with:
          version: 2.50.4
        env:
          JF_ENV_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}

      - name: Configure JFrog Cli
        run: |
          jf mvnc \
            --use-wrapper=true \
            --repo-resolve-releases=libs-milestone \
            --repo-resolve-snapshots=snapshot \
            --repo-deploy-releases=libs-milestone-local \
            --repo-deploy-snapshots=libs-snapshot-local
          echo JFROG_CLI_BUILD_NAME=${{ github.event.repository.name }}-${{ github.ref_name }} >> $GITHUB_ENV
          echo JFROG_CLI_BUILD_NUMBER=$GITHUB_RUN_NUMBER >> $GITHUB_ENV

      - name: Build and Publish
        run: |
          jf mvn install ${{ inputs.mavenArgs }}
          jf rt build-publish

      - name: Capture Test Results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: '**/target/surefire-reports/**/*.*'
          retention-days: 3

